repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: no-commit-to-branch
        args: [--branch, dev, --branch, main]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        files: ^frontend/.*
        types_or: [css, javascript, jsx, ts, tsx, html]
  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet format backend/Onied -v normal --include
        files: ^backend/.*
        types_or: ["c#"]
