include:
  - backend/docker-compose.yml

services:
  frontend:
    image: misergeevkpfu/frontend
    ports:
      - 8080:8080
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - VITE_MAPBOX_API_KEY=
        - VITE_API_URL=
        - VITE_VK_CLIENT_ID=
        - VITE_REDIRECT_URL=
        - VITE_VK_AUTH_URL=https://oauth.vk.com/authorize
    depends_on:
      - users
