apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: certificates
  name: certificates
spec:
  ports:
    - name: "5508"
      port: 5508
      targetPort: 5508
  selector:
    io.kompose.service: certificates
