apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: courses
  name: courses
spec:
  ports:
    - name: "5135"
      port: 5135
      targetPort: 8080
  selector:
    io.kompose.service: courses
