apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert --out k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: courses
  name: courses
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: courses
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert --out k8s/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: courses
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__CoursesDatabase
              value: Host=db;Username=postgres;Password=postgres;Database=courses_database
            - name: PurchasesServerApi
              value: http://purchases:8080/api/v1/purchases/verify
            - name: RabbitMQ__Host
              value: rabbitmq
          image: misergeevkpfu/courses
          name: courses
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
