apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: courses
  name: courses
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: courses
  template:
    metadata:
      labels:
        io.kompose.service: courses
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: courses-config
          image: misergeevkpfu/courses
          name: courses
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
