apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: notifications
  name: notifications
spec:
  ports:
    - name: "5298"
      port: 5298
      targetPort: 8080
  selector:
    io.kompose.service: notifications
