apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: purchases
  name: purchases
spec:
  ports:
    - name: "5036"
      port: 5036
      targetPort: 8080
  selector:
    io.kompose.service: purchases
