apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert --out k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: purchases
  name: purchases
spec:
  ports:
    - name: "5036"
      port: 5036
      targetPort: 8080
  selector:
    io.kompose.service: purchases
