apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert --out k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: purchases
  name: purchases
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: purchases
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert --out k8s/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: purchases
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__PurchasesDatabase
              value: Host=db;Username=postgres;Password=postgres;Database=purchases_database
            - name: RabbitMQ__Host
              value: rabbitmq
          image: misergeevkpfu/purchases
          name: purchases
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
