apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: purchases
  name: purchases
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: purchases
  template:
    metadata:
      labels:
        io.kompose.service: purchases
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__PurchasesDatabase
              value: Host=db;Username=postgres;Password=postgres;Database=purchases_database
            - name: RabbitMQ__Host
              value: rabbitmq
          image: misergeevkpfu/purchases
          name: purchases
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
