apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert --out k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: storage
  name: storage
spec:
  ports:
    - name: "5264"
      port: 5264
      targetPort: 8080
  selector:
    io.kompose.service: storage
