apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: storage
  name: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: storage
  template:
    metadata:
      labels:
        io.kompose.service: storage
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          image: misergeevkpfu/storage
          name: storage
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
