apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: storage
  name: storage
spec:
  ports:
    - name: "5264"
      port: 5264
      targetPort: 8080
  selector:
    io.kompose.service: storage
