apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert --out k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: support
  name: support
spec:
  ports:
    - name: "5226"
      port: 5226
      targetPort: 8080
  selector:
    io.kompose.service: support
