apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: support
  name: support
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: support
  template:
    metadata:
      labels:
        io.kompose.service: support
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__SupportDatabase
              value: Host=db;Username=postgres;Password=postgres;Database=support_database
            - name: RabbitMQ__Host
              value: rabbitmq
          image: misergeevkpfu/support
          name: support
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
