apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: support
  name: support
spec:
  ports:
    - name: "5226"
      port: 5226
      targetPort: 8080
  selector:
    io.kompose.service: support
