apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: users
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: users
  template:
    metadata:
      labels:
        io.kompose.service: users
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__UsersDatabase
              value: Host=db;Username=postgres;Password=postgres;Database=users_database
            - name: RabbitMQ__Host
              value: rabbitmq
          image: misergeevkpfu/users
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/healthz
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 5
          name: users
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
