apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: users
  name: users
spec:
  ports:
    - name: "5288"
      port: 5288
      targetPort: 8080
  selector:
    io.kompose.service: users
