apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ConnectionStrings__NotificationsDatabase: Host=db;Username=postgres;Password=postgres;Database=notifications_database
  RabbitMQ__Host: rabbitmq
