services:
  db:
    image: misergeevkpfu/postgres
    build:
      context: .
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
