name: Publish Docker Images

on: [push]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    DATABASE_HOST: localhost
    DATABASE_PORT: 5432
    DATABASE_USER: postgres
    DATABASE_PASS: postgres
    DATABASE_NAME: certificates_database
    MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}  # Используйте секреты для чувствительных данных
    MAPBOX_API_URL: https://api.mapbox.com/search/geocode/v6/forward
    PURCHASES_API_URL: http://localhost:5036/api/v1/purchases/verify
    RABBITMQ_CONNECTION_STRING: amqp://guest:guest@localhost:5672
                
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
      
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
