name: Publish Docker Images

on:
  release:
    types: [published]

env:
    PROJECT_NAME: onied
    SITE: https://onied.com
  
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Setting environmental variables
              run: |
                cat <<EOF > docker-compose.override.yml 
                services:
                  frontend:
                    restart: unless-stopped
                    build:
                      args:
                        VITE_MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
                        VITE_API_URL: ${{ env.SITE }}/api/v1/
                        VITE_VK_CLIENT_ID: ${{ secrets.VK_CLIENT_ID }}
                        VITE_REDIRECT_URL: ${{ env.SITE }}/oauth-redirect
                        VITE_VK_AUTH_URL: https://oauth.vk.com/authorize
                  users:
                    restart: unless-stopped
                    environment:
                      ASPNETCORE_ENVIRONMENT: Production
                      Authentication__VK__ClientId: ${{ secrets.VK_CLIENT_ID }}
                      Authentication__VK__ClientSecret: ${{ secrets.VK_CLIENT_SECRET }}
                  courses:
                    restart: unless-stopped
                    environment:
                      ASPNETCORE_ENVIRONMENT: Production
                  notifications:
                    restart: unless-stopped
                    environment:
                      ASPNETCORE_ENVIRONMENT: Production
                  purchases:
                    restart: unless-stopped
                    environment:
                      ASPNETCORE_ENVIRONMENT: Production
                  certificates:
                    restart: unless-stopped
                    environment:
                      MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
                EOF
            
            - name: Build Docker images
              run: docker compose -f docker-compose.yml -f docker-compose.override.yml build --no-cache

            - name: Push Docker images
              run: docker compose -f docker-compose.yml -f docker-compose.override.yml push
