name: Publish Docker Images

on:
  release:
    types: [published]

env:
    REGISTRY: ghcr.io
    
    IMAGE_NAME: ${{ github.repository }}
    PROJECT_NAME: onied
    DATABASE_HOST: localhost
    DATABASE_PORT: 5432
    DATABASE_USER: postgres
    DATABASE_PASS: postgres
    DATABASE_NAME: certificates_database
    MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
    MAPBOX_API_URL: https://api.mapbox.com/search/geocode/v6/forward
    PURCHASES_API_URL: http://localhost:5036/api/v1/purchases/verify
    RABBITMQ_CONNECTION_STRING: amqp://guest:guest@localhost:5672
  
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            # - name: Build Docker images
            #   run: docker compose build

            # - name: Push Docker images
            #   run: docker compose push

            - name: Create a tarball of the docker-compose directory
              run: tar -czf ${{ env.PROJECT_NAME }}.tar.gz ./*

            - name: Copy tarball to remote server
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                port: ${{ secrets.SSH_PORT }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_CD_KEY }}
                source: ${{ env.PROJECT_NAME }}.tar.gz
                target: ~/onied

            - name: SSH to remote server and deploy with Docker Compose
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                port: ${{ secrets.SSH_PORT }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_CD_KEY }}
                script: |
                  if [ $(docker container ls -q --filter name='misergeeevkpfu*' | wc -l) -gt 0 ]; then
                      docker stop $(docker container ls -q --filter name='misergeeevkpfu*');
                  else
                      echo 'No matching containers to stop.';
                  fi
                  cd ~/${{ env.PROJECT_NAME }}
                  tar -xzf ${{ env.PROJECT_NAME }}.tar.gz
                  docker compose pull
                  docker compose up -d
