name: Publish Docker Images

on: [push]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    DATABASE_HOST: localhost
    DATABASE_PORT: 5432
    DATABASE_USER: postgres
    DATABASE_PASS: postgres
    DATABASE_NAME: certificates_database
    MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}  # Используйте секреты для чувствительных данных
    MAPBOX_API_URL: https://api.mapbox.com/search/geocode/v6/forward
    PURCHASES_API_URL: http://localhost:5036/api/v1/purchases/verify
    RABBITMQ_CONNECTION_STRING: amqp://guest:guest@localhost:5672
  
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            # - name: Log in to the Container registry
            #   uses: docker/login-action@v3
            #   with:
            #     registry: ${{ env.REGISTRY }}
            #     username: ${{ github.actor }}
            #     password: ${{ secrets.PAT }}
            
            # - name: Build Docker images
            #   run: docker compose build

            # - name: Publish Docker images
            #   run: docker compose push
            - name: Docker-Compose Remote Deployment
              uses: alex-ac/github-action-ssh-docker-compose@master
              with:
                ssh_host: ${{ secrets.SSH_HOST }}
                ssh_port: ${{ secrets.SSH_PORT }}
                ssh_user: ${{ secrets.SSH_USER }}
                ssh_private_key: ${{ secrets.SSH_CD_KEY }}
                docker_compose_prefix: onied
