name: onied_mobile
description: "A moble app for the OniEd website."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  logging: ^1.3.0
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.7
  webview_flutter: ^4.0.0
  collection: ^1.17.0
  flutter_credit_card: ^4.1.0
  http: ^1.3.0
  app_links: ^3.1.0
  flutter_web_auth_2: ^4.0.2
  go_router: ^15.1.1
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.otf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Inter-Light.otf
          weight: 300
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Inter-Black.otf
          weight: 900
